import { useState, useEffect, useRef, useCallback } from "react";

const D = {
  email:"gnanaganeshgm@gmail.com",phone:"+91-8190976506",location:"Bengaluru, Karnataka",
  li:"https://www.linkedin.com/in/gnana-ganesh-m/",gh:"https://github.com/gnaanmohan2118",tw:"https://twitter.com/53agati",
  map:"https://maps.app.goo.gl/DqCpEaK8F9yYFexo7",form:"https://formspree.io/f/xjkovypw",
  roles:["Software Engineer at Oracle","AWS Solutions Architect","Terraform Associate Certified","Cloud & DevOps Specialist","Gen AI Engineer","CS50W Certified"],
  skills:[["Python (OOP, Scripting)",90],["Django / FastAPI",85],["AWS (EC2, EKS, Lambda, S3)",95],["Docker / Kubernetes",88],["Terraform / Ansible",95],["CI/CD (GitHub Actions)",90],["LangChain / RAG / LLMs",80],["Nginx / Redis",80],["Prometheus / Grafana",80],["SQL / NoSQL",88],["Shell / Linux",90],["Microservices",85]],
  oracle:{company:"Oracle",role:"Software Engineer",period:"Feb 2026 / Present",color:"#c74634",gradient:"linear-gradient(135deg,#c74634,#ff6b4a,#c74634)",tagline:"Where I innovate.",desc:"Driving greenfield POCs for global banking products. Building secure GenAI, computer vision, and agentic AI systems in air-gapped enterprise environments.",points:["Driving multiple greenfield POCs for global banking, building production-aligned GenAI and computer vision systems within fully air-gapped environments.","Designing GenAI-driven event monitoring dashboards with LLM workflows for contextual alert analysis and intelligent summarization.","Developing CNN-based models and OCR pipelines achieving 95%+ classification accuracy in enterprise banking.","Establishing secure model packaging with version-controlled artifacts and reproducible build processes.","Contributing to an internal Agentic AI framework with modular agents for workflow automation."]},
  accenture:{company:"Accenture",role:"Associate Software Engineer",period:"Feb 2024 / Feb 2026",color:"#a100ff",gradient:"linear-gradient(135deg,#a100ff,#c850ff,#a100ff)",tagline:"Where I built.",desc:"ERP platforms, Gen AI apps, and cloud infrastructure serving thousands. Every deploy mattered.",points:["Developed scalable ERP modules using Python, JavaScript, and AWS RDS, supporting 2,500+ users, maintaining over 99.5% uptime.","Engineered secure internal GenAI knowledge retrieval system integrating LLM APIs for context-aware code generation.","Migrated legacy on-prem databases to AWS (RDS, DynamoDB) using SQS, Lambda, Glue ETL with zero-downtime.","Automated CI/CD pipelines with GitHub, CodePipeline, Terraform, CloudFormation, and Kubernetes.","Awarded ACE Award for resolving high-impact production issues."]},
  passions:[{emoji:"",title:"Bike Rides & Road Trips",desc:"Mountain passes to coastal roads. Therapy, freedom, and adventure.",tags:["All-India Tour","Solo Rides"],color:"#ff6b35"},{emoji:"",title:"Photography",desc:"Landscapes, street scenes, and the quiet beauty in everyday moments.",tags:["Landscapes","Street","Travel"],color:"#0071e3"},{emoji:"",title:"Travel & Exploration",desc:"New places, new cultures, new perspectives.",tags:["India Explorer","Adventure"],color:"#30d158"}],
  blogs:[{tag:"Society",title:"On Being Open-Minded in a Closed World",excerpt:"Why questioning norms is not rebellion. It is responsibility.",color:"#5856d6"},{tag:"Tech & Life",title:"What DevOps Taught Me About Life",excerpt:"Iteration, resilience, and continuous improvement are life skills.",color:"#0071e3"},{tag:"Travel",title:"1,000 Kilometres on Two Wheels",excerpt:"Breakdowns, sunsets, and everything in between.",color:"#30d158"}]
};

function useVis(th=0.1){const r=useRef(null);const[v,s]=useState(false);useEffect(()=>{const el=r.current;if(!el)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting)s(true)},{threshold:th});o.observe(el);return()=>o.disconnect()},[]);return[r,v]}
function R({children,d=0,dir="up",style={}}){const[r,v]=useVis();const t={up:"translateY(32px)",left:"translateX(-32px)",right:"translateX(32px)"};return<div ref={r} style={{opacity:v?1:0,transform:v?"none":t[dir],transition:`opacity .7s cubic-bezier(.16,1,.3,1) ${d}s, transform .7s cubic-bezier(.16,1,.3,1) ${d}s`,...style}}>{children}</div>}
function useTheme(){const[t,s]=useState(()=>localStorage.getItem("gmg-t")||"light");useEffect(()=>{document.documentElement.setAttribute("data-theme",t);localStorage.setItem("gmg-t",t)},[t]);return[t,()=>s(p=>p==="dark"?"light":"dark")]}
function useScrollProgress(ref){const[p,setP]=useState(0);useEffect(()=>{const h=()=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();const vh=window.innerHeight;setP(Math.max(0,Math.min(1,(vh-r.top)/(vh+r.height))))};addEventListener("scroll",h,{passive:true});h();return()=>removeEventListener("scroll",h)},[]);return p}

function Typer(){const[idx,setIdx]=useState(0);const[text,setText]=useState("");const[del,setDel]=useState(false);useEffect(()=>{const target=D.roles[idx];let timer;if(!del){if(text.length<target.length)timer=setTimeout(()=>setText(target.slice(0,text.length+1)),50);else timer=setTimeout(()=>setDel(true),2200)}else{if(text.length>0)timer=setTimeout(()=>setText(text.slice(0,-1)),25);else{setDel(false);setIdx((idx+1)%D.roles.length)}}return()=>clearTimeout(timer)},[text,del,idx]);return<span style={{color:"var(--acc)"}}>{text}<span style={{display:"inline-block",width:2,height:"1.1em",background:"var(--acc)",marginLeft:2,verticalAlign:"text-bottom",animation:"blink 1s step-end infinite"}}/></span>}
function NameReveal(){const[s,set]=useState(false);useEffect(()=>{setTimeout(()=>set(true),400)},[]);return<h1 style={{fontFamily:"var(--fd)",fontSize:"clamp(60px,12vw,110px)",fontWeight:900,lineHeight:.95,letterSpacing:-5}}><span style={{display:"block",overflow:"hidden"}}>{"Gnana".split("").map((c,i)=><span key={i} style={{display:"inline-block",color:"var(--ink)",opacity:s?1:0,transform:s?"none":"translateY(60px) rotate(8deg)",transition:`all .6s cubic-bezier(.16,1,.3,1) ${.5+i*.06}s`}}>{c}</span>)}</span><span style={{display:"block",overflow:"hidden"}}>{"Ganesh.!".split("").map((c,i)=><span key={i} style={{display:"inline-block",background:"linear-gradient(135deg,var(--acc),#34aadc,#5ac8fa)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",opacity:s?1:0,transform:s?"none":"translateY(60px) rotate(-8deg)",transition:`all .6s cubic-bezier(.16,1,.3,1) ${.8+i*.06}s`}}>{c}</span>)}</span></h1>}
function Particles(){const ref=useRef(null);const pts=useRef([]);const mouse=useRef({x:-999,y:-999});const af=useRef(null);useEffect(()=>{const c=ref.current;const ctx=c.getContext("2d");let W,H;const rs=()=>{W=c.width=c.offsetWidth;H=c.height=c.offsetHeight};rs();addEventListener("resize",rs);for(let i=0;i<50;i++)pts.current.push({x:Math.random()*W,y:Math.random()*H,vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35,r:Math.random()*1.8+.4});const draw=()=>{ctx.clearRect(0,0,W,H);const dk=document.documentElement.getAttribute("data-theme")==="dark";const dc=dk?"41,151,255":"0,113,227";pts.current.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=W;if(p.x>W)p.x=0;if(p.y<0)p.y=H;if(p.y>H)p.y=0;const dx=mouse.current.x-p.x,dy=mouse.current.y-p.y,dist=Math.sqrt(dx*dx+dy*dy);const g=dist<200?(200-dist)/200:0;ctx.beginPath();ctx.arc(p.x,p.y,p.r+g*3,0,Math.PI*2);ctx.fillStyle=`rgba(${dc},${.12+g*.6})`;ctx.fill()});pts.current.forEach((p,i)=>{pts.current.slice(i+1).forEach(q=>{const d=Math.sqrt((p.x-q.x)**2+(p.y-q.y)**2);if(d<110){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=`rgba(${dc},${.05*(1-d/110)})`;ctx.lineWidth=.5;ctx.stroke()}})});af.current=requestAnimationFrame(draw)};draw();const onM=e=>{const r=c.getBoundingClientRect();mouse.current={x:e.clientX-r.left,y:e.clientY-r.top}};c.addEventListener("mousemove",onM);return()=>{removeEventListener("resize",rs);c.removeEventListener("mousemove",onM);cancelAnimationFrame(af.current)}},[]);return<canvas ref={ref} style={{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"auto",zIndex:0}}/>}
function MagneticPhoto(){const[s,set]=useState(false);const[tilt,setTilt]=useState({x:0,y:0});const ref=useRef(null);useEffect(()=>{setTimeout(()=>set(true),200)},[]);const onMove=useCallback(e=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();const x=(e.clientX-(r.left+r.width/2))/12,y=(e.clientY-(r.top+r.height/2))/12;setTilt({x:Math.max(-15,Math.min(15,y)),y:Math.max(-15,Math.min(15,-x))})},[]);return<div ref={ref} onMouseMove={onMove} onMouseLeave={()=>setTilt({x:0,y:0})} style={{position:"relative",width:180,height:180,marginBottom:28,perspective:600,opacity:s?1:0,transform:s?"scale(1)":"scale(.6)",transition:"opacity .8s cubic-bezier(.16,1,.3,1) .15s, transform .8s cubic-bezier(.16,1,.3,1) .15s"}}><div style={{position:"absolute",inset:-8,borderRadius:"50%",background:"conic-gradient(from 0deg,var(--acc),#5ac8fa,#34aadc,#be5df7,var(--acc))",animation:"spinSlow 3s linear infinite",opacity:s?.5:0,transition:"opacity 1s ease .5s",filter:"blur(4px)"}}/><div style={{width:180,height:180,borderRadius:"50%",overflow:"hidden",border:"4px solid var(--card)",boxShadow:"0 0 50px rgba(0,113,227,.2)",position:"relative",zIndex:1,transform:`rotateX(${tilt.x}deg) rotateY(${tilt.y}deg)`,transition:"transform .15s ease"}}><img src="/img/ganeshhachiko.png" alt="Gnana Ganesh" style={{width:"100%",height:"100%",objectFit:"cover",objectPosition:"center 20%"}}/></div></div>}

function ExpDevice({data}){const ref=useRef(null);const p=useScrollProgress(ref);const rX=35-p*45,rY=-20+p*25,sc=.8+p*.25,sb=20+p*40;
return<div ref={ref} style={{display:"grid",gridTemplateColumns:"5fr 7fr",gap:40,alignItems:"center",marginBottom:100,minHeight:500}} className="sg">
  <R dir="left"><div><p style={{fontFamily:"var(--fm)",fontSize:12,letterSpacing:2,textTransform:"uppercase",color:data.color,marginBottom:14}}>{data.period}</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(40px,6vw,64px)",fontWeight:900,letterSpacing:-2.5,lineHeight:1.0}}><span style={{color:data.color}}>{data.company}.</span><br/>{data.tagline}</h2><p style={{fontSize:18,fontWeight:300,color:"var(--ink2)",lineHeight:1.65,marginTop:24,maxWidth:400}}>{data.desc}</p><div style={{marginTop:20}}><Pill color={data.color}>{data.role}</Pill></div></div></R>
  <div style={{perspective:1200,display:"flex",justifyContent:"center",alignItems:"center"}}><div style={{width:"100%",maxWidth:560,transform:`rotateX(${rX}deg) rotateY(${rY}deg) scale(${sc})`,transition:"transform .05s linear",transformStyle:"preserve-3d"}}><div style={{background:"#1a1a1a",borderRadius:20,padding:"16px 16px 24px",boxShadow:`0 ${sb}px ${sb*2}px rgba(0,0,0,${.08+p*.12}), 0 0 0 1px rgba(255,255,255,.05) inset`}}><div style={{background:data.gradient,borderRadius:12,padding:"28px 24px",minHeight:380,display:"flex",flexDirection:"column",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",inset:0,opacity:.06,backgroundImage:"linear-gradient(rgba(255,255,255,.3) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.3) 1px, transparent 1px)",backgroundSize:"40px 40px"}}/><div style={{display:"flex",alignItems:"center",gap:14,marginBottom:24,position:"relative",zIndex:1}}><div style={{width:52,height:52,borderRadius:16,background:"rgba(255,255,255,.2)",backdropFilter:"blur(10px)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:26,fontWeight:900,color:"#fff",fontFamily:"var(--fd)"}}>{data.company[0]}</div><div><p style={{fontFamily:"var(--fd)",fontWeight:700,fontSize:20,color:"#fff"}}>{data.company}</p><p style={{fontSize:13,color:"rgba(255,255,255,.7)"}}>{data.role}</p></div></div><div style={{display:"flex",flexDirection:"column",gap:12,position:"relative",zIndex:1}}>{data.points.map((pt,i)=><div key={i} style={{display:"flex",gap:10,fontSize:14,lineHeight:1.55,color:"rgba(255,255,255,.9)"}}><span style={{color:"rgba(255,255,255,.5)",fontFamily:"var(--fm)",fontWeight:700,flexShrink:0,marginTop:1}}>0{i+1}</span><span>{pt}</span></div>)}</div></div></div><div style={{height:12,background:"linear-gradient(180deg,#2a2a2a,#1a1a1a)",borderRadius:"0 0 8px 8px",margin:"0 40px",boxShadow:"0 4px 12px rgba(0,0,0,.15)"}}/><div style={{height:4,background:"#333",borderRadius:"0 0 4px 4px",margin:"0 80px"}}/></div></div>
</div>}

function ProvenImpact(){const ref=useRef(null);const ip=useScrollProgress(ref);const radius=Math.max(0,28-ip*56),margin=Math.max(0,40-ip*80);
return<section ref={ref} style={{padding:`20px ${margin}px`,transition:"padding .05s linear"}}><div style={{position:"relative",overflow:"hidden",borderRadius:radius,minHeight:"85vh",display:"flex",alignItems:"center",justifyContent:"center",padding:"100px 40px",transition:"border-radius .05s linear"}}>
  <div style={{position:"absolute",inset:0,background:"linear-gradient(135deg,#2d1b69 0%,#1a237e 20%,#0d47a1 40%,#00695c 60%,#1b5e20 75%,#4a148c 100%)"}}/>
  <div style={{position:"absolute",left:"5%",top:"-10%",width:120,height:"120%",borderRadius:60,background:"linear-gradient(180deg,rgba(149,117,205,.5),rgba(66,66,180,.3))",boxShadow:"inset 0 0 40px rgba(255,255,255,.08), 0 0 60px rgba(149,117,205,.15)"}}/>
  <div style={{position:"absolute",left:"16%",top:"-5%",width:100,height:"115%",borderRadius:50,background:"linear-gradient(180deg,rgba(100,100,220,.4),rgba(30,60,180,.25))",boxShadow:"inset 0 0 30px rgba(255,255,255,.06)"}}/>
  <div style={{position:"absolute",left:"27%",top:"-8%",width:130,height:"120%",borderRadius:65,background:"linear-gradient(180deg,rgba(70,130,230,.35),rgba(20,100,180,.2))",boxShadow:"inset 0 0 40px rgba(255,255,255,.05)"}}/>
  <div style={{position:"absolute",right:"25%",top:"-12%",width:110,height:"125%",borderRadius:55,background:"linear-gradient(180deg,rgba(0,150,136,.35),rgba(56,142,60,.2))",boxShadow:"inset 0 0 30px rgba(255,255,255,.06)"}}/>
  <div style={{position:"absolute",right:"12%",top:"-5%",width:140,height:"118%",borderRadius:70,background:"linear-gradient(180deg,rgba(156,39,176,.4),rgba(103,58,183,.25))",boxShadow:"inset 0 0 40px rgba(255,255,255,.07)"}}/>
  <div style={{position:"absolute",right:"0%",top:"-10%",width:100,height:"120%",borderRadius:50,background:"linear-gradient(180deg,rgba(186,130,245,.35),rgba(120,80,200,.2))",boxShadow:"inset 0 0 30px rgba(255,255,255,.05)"}}/>
  <div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%)",width:420,height:420,borderRadius:"50%",background:"radial-gradient(circle at 40% 35%,rgba(255,255,255,.12),rgba(255,255,255,.04) 60%,transparent 75%)",boxShadow:"inset 0 0 80px rgba(255,255,255,.06)"}}/>
  <div style={{position:"absolute",top:"15%",left:"35%",width:180,height:180,borderRadius:"50%",background:"radial-gradient(circle at 45% 40%,rgba(255,255,255,.08),transparent 65%)"}}/>
  <div style={{position:"absolute",bottom:"20%",right:"30%",width:150,height:150,borderRadius:"50%",background:"radial-gradient(circle at 50% 45%,rgba(255,255,255,.06),transparent 65%)"}}/>
  <div style={{position:"relative",zIndex:1,textAlign:"center",maxWidth:1000}}>
    <p style={{fontFamily:"var(--fm)",fontSize:13,letterSpacing:3,textTransform:"uppercase",color:"rgba(245,245,247,.6)",marginBottom:20}}>Proven Impact</p>
    <h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(48px,8vw,84px)",fontWeight:900,letterSpacing:-3.5,color:"#f5f5f7",lineHeight:1.0,marginBottom:20}}>Numbers that<br/>speak for themselves.</h2>
    <p style={{fontSize:19,fontWeight:400,color:"rgba(245,245,247,.6)",maxWidth:600,margin:"0 auto 80px",lineHeight:1.6}}>2+ years engineering production systems that scale. From enterprise banking platforms to cloud-native AI infrastructure, the numbers tell the story.</p>
    <div style={{display:"flex",justifyContent:"center",gap:72,flexWrap:"wrap"}}>
      {[{v:"2,500+",l:"Users Served",sub:"Production ERP at scale"},{v:"99.5%",l:"System Uptime",sub:"Enterprise reliability"},{v:"95%+",l:"ML Accuracy",sub:"CNN document intelligence"},{v:"Zero",l:"Downtime Deploys",sub:"Continuous delivery"}].map(s=><div key={s.l} style={{textAlign:"center"}}><div style={{fontFamily:"var(--fd)",fontSize:"clamp(48px,7vw,76px)",fontWeight:900,letterSpacing:-3,background:"linear-gradient(180deg,rgba(255,255,255,1) 0%,rgba(255,255,255,.7) 100%)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",lineHeight:1}}>{s.v}</div><p style={{fontSize:15,fontWeight:600,color:"rgba(245,245,247,.85)",marginTop:10}}>{s.l}</p><p style={{fontSize:12,color:"rgba(245,245,247,.35)",marginTop:4}}>{s.sub}</p></div>)}
    </div>
  </div>
</div></section>}

const CertIcon=({type})=>{const s={width:56,height:56};
if(type==="aws")return<svg viewBox="0 0 48 48" style={s}><path d="M13.5 21.6c0 .7.1 1.2.3 1.6.2.4.4.8.8 1.2.1.2.2.3.2.5s-.1.3-.3.5l-1 .7c-.2.1-.3.2-.4.2-.2 0-.3-.1-.5-.3-.3-.3-.5-.6-.7-.9-.2-.3-.4-.7-.6-1.1-1.6 1.9-3.6 2.8-6 2.8-1.7 0-3.1-.5-4.1-1.5S0 23.5 0 22.1c0-1.5.5-2.8 1.6-3.7 1.1-1 2.5-1.4 4.3-1.4.6 0 1.2 0 1.9.1s1.3.2 2 .4v-1.3c0-1.3-.3-2.2-.8-2.8-.6-.6-1.5-.8-2.9-.8-.6 0-1.3.1-1.9.2-.7.2-1.3.4-1.9.6-.3.1-.5.2-.6.2h-.3c-.2 0-.3-.2-.3-.5v-.8c0-.3 0-.5.1-.6.1-.1.2-.3.5-.4.6-.3 1.4-.6 2.2-.8.9-.2 1.8-.4 2.8-.4 2.1 0 3.7.5 4.6 1.5 1 1 1.4 2.5 1.4 4.5v5.9zm-8.2 3.1c.6 0 1.2-.1 1.8-.3.7-.2 1.2-.6 1.7-1.1.3-.3.5-.7.6-1.1.1-.4.2-.9.2-1.5v-.7c-.5-.1-1.1-.2-1.6-.3-.6-.1-1.1-.1-1.6-.1-1.2 0-2 .2-2.6.7-.6.5-.9 1.2-.9 2.1 0 .8.2 1.5.6 1.9.5.3 1.1.4 1.8.4z" fill="#FF9900"/><path d="M45.4 33.5c-5.6 4.1-13.6 6.3-20.6 6.3-9.7 0-18.5-3.6-25.1-9.6-.5-.5-.1-1.1.6-.8 7.1 4.2 16 6.7 25.1 6.7 6.2 0 12.9-1.3 19.1-3.9.9-.4 1.7.6.9 1.3z" fill="#FF9900"/><path d="M47.4 31.1c-.7-.9-4.8-.4-6.6-.2-.6.1-.6-.4-.1-.8 3.2-2.3 8.5-1.6 9.1-.8.6.8-.2 6.2-3.2 8.8-.5.4-.9.2-.7-.3.7-1.7 2.2-5.7 1.5-6.7z" fill="#FF9900"/></svg>;
if(type==="tf")return<svg viewBox="0 0 48 48" style={s}><polygon points="20.1,5 20.1,17.3 30.7,23.4 30.7,11.1" fill="#7B42BC"/><polygon points="30.7,23.4 30.7,11.1 41.3,17.3 41.3,29.6" fill="#4040B2"/><polygon points="9.4,11.1 9.4,23.4 20.1,29.6 20.1,17.3" fill="#7B42BC"/><polygon points="20.1,31.5 20.1,43.8 30.7,37.7 30.7,25.4" fill="#7B42BC"/></svg>;
if(type==="cs50")return<svg viewBox="0 0 48 48" style={s}><rect x="4" y="8" width="40" height="32" rx="4" fill="#A51C30"/><path d="M14 28l5-5-5-5" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" fill="none"/><line x1="23" y1="28" x2="34" y2="28" stroke="#fff" strokeWidth="2.5" strokeLinecap="round"/><text x="24" y="15" textAnchor="middle" fill="rgba(255,255,255,.5)" fontSize="5.5" fontWeight="700" fontFamily="monospace">CS50W</text></svg>;
if(type==="cka")return<svg viewBox="0 0 48 48" style={s}><circle cx="24" cy="24" r="20" fill="#326CE5"/><path d="M24 10l-3 7h-7l5.5 4.5-2 7L24 24l6.5 4.5-2-7L34 17h-7z" fill="#fff"/></svg>;
return null};

function CertShowcase(){
  const certs=[{type:"aws",title:"AWS Solutions Architect.",desc:"Associate certified. Distributed systems, cost-optimized architectures, and resilient infrastructure on AWS.",link:"https://www.credly.com/badges/8d72832f-5647-44af-89b1-12697b8e7a2c",tags:["Cloud","Architecture","AWS"],gradient:"linear-gradient(135deg,#1a1a2e,#2d1b00,#4a2600)"},{type:"tf",title:"Terraform Associate.",desc:"HashiCorp certified. Infrastructure as Code, multi-cloud provisioning, state management, and modular deploys.",link:"https://www.credly.com/badges/1c450a47-9ce7-4f92-9358-23ef04229bcb/",tags:["IaC","Multi-cloud","HCL"],gradient:"linear-gradient(135deg,#1a0a2e,#2d1555,#1a0a2e)"},{type:"cs50",title:"CS50W Certified.",desc:"Harvard / edX. Full-stack web with Python, JavaScript, Django, SQL, and modern frontend frameworks.",tags:["Harvard","Python","Django"],gradient:"linear-gradient(135deg,#2a0a0a,#4a1020,#2a0a0a)"},{type:"cka",title:"Kubernetes (CKA).",desc:"In progress. Cluster architecture, workload scheduling, networking, storage, and security.",tags:["K8s","Containers","Orchestration"],gradient:"linear-gradient(135deg,#0a1a3e,#132d5e,#0a1a3e)"}];
  return<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:20}} className="g3r">{certs.map((c,i)=><R key={c.type} d={i*.08}><div style={{display:"flex",flexDirection:"column",height:"100%"}}><div style={{height:320,borderRadius:20,overflow:"hidden",position:"relative",marginBottom:16}}><div style={{position:"absolute",inset:0,background:c.gradient}}/><div style={{position:"absolute",top:"12%",right:"10%",width:140,height:140,borderRadius:"50%",background:"rgba(255,255,255,.04)"}}/><div style={{position:"absolute",bottom:"15%",left:"8%",width:100,height:100,borderRadius:"50%",background:"rgba(255,255,255,.03)"}}/><div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%)",opacity:.9}}><CertIcon type={c.type}/></div><div style={{position:"absolute",bottom:14,left:14,display:"flex",gap:5}}>{c.tags.map(t=><span key={t} style={{fontFamily:"var(--fm)",fontSize:9,fontWeight:600,padding:"3px 8px",borderRadius:99,background:"rgba(255,255,255,.1)",backdropFilter:"blur(8px)",color:"rgba(255,255,255,.75)",letterSpacing:.3}}>{t}</span>)}</div></div><p style={{fontSize:15,lineHeight:1.55,color:"var(--ink2)"}}><strong style={{color:"var(--ink)",fontWeight:700}}>{c.title}</strong>{" "}{c.desc}</p>{c.link&&<a href={c.link} target="_blank" rel="noopener noreferrer" style={{fontSize:13,fontWeight:500,marginTop:8,color:"var(--acc)",textDecoration:"none",display:"inline-block"}}>View credential &gt;</a>}</div></R>)}</div>
}

function ProjectGrid(){
  const projects=[{title:"Real-time AI, zero latency.",desc:"WebSocket chat with RAG pipeline and Groq API. Sub-200ms responses, Redis messaging, JWT secured. Containerized MLOps on Kubernetes.",link:"https://gurubaba-ai.guru/",tags:["FastAPI","RAG","K8s","Redis"],gradient:"linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)",accent:"#667eea",terminal:["$ groq serve --model mixtral","Loading RAG pipeline...","Indexing 12k vectors...","✓ WebSocket ready on :8000","$ latency: 142ms avg"]},{title:"Jobs that never fail.",desc:"Distributed scheduler with exponential backoff, dead-letter queues, and priority execution. Real-time telemetry via Prometheus and Splunk.",tags:["Python","Redis","Docker","Prometheus"],gradient:"linear-gradient(135deg,#0f0c29,#302b63,#24243e)",accent:"#f093fb",terminal:["$ scheduler start --workers 8","Registering job queues...","Backoff policy: exponential","✓ 0 failed / 2.4k processed","$ health: all workers alive"]},{title:"Short links, long uptime.",desc:"Base62 URL shortener with TTL caching, blue-green deployments, and full observability. Zero-downtime releases on AWS.",tags:["AWS","Terraform","Nginx","PostgreSQL"],gradient:"linear-gradient(135deg,#0c3547,#1a5276,#0e6655)",accent:"#4facfe",terminal:["$ terraform apply --auto","Creating EC2 instances...","Nginx config: blue-green","✓ DNS propagated globally","$ uptime: 99.99%"]}];
  return<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:20}} className="g3r">{projects.map((p,i)=><R key={p.title} d={i*.08}><div style={{display:"flex",flexDirection:"column",height:"100%"}}><div style={{height:320,borderRadius:20,overflow:"hidden",position:"relative",marginBottom:16}}><div style={{position:"absolute",inset:0,background:p.gradient}}/><div style={{position:"absolute",top:"12%",right:"8%",width:160,height:160,borderRadius:"50%",background:`radial-gradient(circle,${p.accent}25,transparent 70%)`,filter:"blur(25px)"}}/><div style={{position:"absolute",bottom:"8%",left:"10%",width:120,height:120,borderRadius:"50%",background:`radial-gradient(circle,${p.accent}15,transparent 70%)`,filter:"blur(20px)"}}/><div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%) perspective(600px) rotateX(3deg)",width:"80%",maxWidth:280}}><div style={{background:"rgba(0,0,0,.55)",backdropFilter:"blur(16px)",borderRadius:10,border:"1px solid rgba(255,255,255,.08)",overflow:"hidden"}}><div style={{display:"flex",gap:5,padding:"8px 12px",borderBottom:"1px solid rgba(255,255,255,.06)"}}><div style={{width:8,height:8,borderRadius:"50%",background:"#ff5f57"}}/><div style={{width:8,height:8,borderRadius:"50%",background:"#febc2e"}}/><div style={{width:8,height:8,borderRadius:"50%",background:"#28c840"}}/></div><div style={{padding:"12px 14px",fontFamily:"var(--fm)",fontSize:11,lineHeight:1.7,color:"rgba(255,255,255,.6)"}}>{p.terminal.map((line,j)=><div key={j} style={{color:line.startsWith("$")?"rgba(255,255,255,.85)":line.startsWith("✓")?"#28c840":"rgba(255,255,255,.45)"}}>{line.startsWith("$")?<><span style={{color:p.accent}}>$</span>{line.slice(1)}</>:line}</div>)}</div></div></div><div style={{position:"absolute",bottom:14,left:14,display:"flex",gap:5,zIndex:2}}>{p.tags.map(t=><span key={t} style={{fontFamily:"var(--fm)",fontSize:9,fontWeight:600,padding:"3px 8px",borderRadius:99,background:"rgba(255,255,255,.1)",backdropFilter:"blur(8px)",color:"rgba(255,255,255,.75)",letterSpacing:.3}}>{t}</span>)}</div></div><div><p style={{fontSize:15,lineHeight:1.55,color:"var(--ink2)"}}><strong style={{color:"var(--ink)",fontWeight:700}}>{p.title}</strong>{" "}{p.desc}</p>{p.link&&<a href={p.link} target="_blank" rel="noopener noreferrer" style={{fontSize:13,fontWeight:500,marginTop:8,color:"var(--acc)",textDecoration:"none",display:"inline-block"}}>View live &gt;</a>}</div></div></R>)}</div>
}

const CATS=[{name:"Core Languages & Databases",pct:80,color:"#0071e3",techs:["Python (OOP, scripting)","SQL, NoSQL","Shell scripting"]},{name:"Backend & Architecture",pct:80,color:"#5856d6",techs:["Django","FastAPI","REST APIs","WebSockets","Microservices"]},{name:"Generative AI & ML",pct:85,color:"#30d158",techs:["LangChain","LangGraph","RAG-based LLM apps","Model fine-tuning","Prompt engineering"]},{name:"Cloud & Infrastructure",pct:95,color:"#ff9500",techs:["AWS (EC2, EKS, Lambda, S3, RDS)","Azure","Terraform","Ansible"]},{name:"Containerization & DevOps",pct:90,color:"#ff453a",techs:["Docker","Kubernetes","GitHub Actions","CI/CD pipelines","SonarQube"]},{name:"Systems & Observability",pct:85,color:"#5ac8fa",techs:["Nginx","Redis","Linux","Prometheus","Grafana","Splunk"]}];
function ScrollSkills(){const[active,setActive]=useState(0);const secRef=useRef(null);const p=useScrollProgress(secRef);useEffect(()=>{const idx=Math.min(CATS.length-1,Math.floor(p*CATS.length*1.2));if(idx>=0&&idx<CATS.length)setActive(idx)},[p]);
return<div ref={secRef}><R><div style={{textAlign:"center",marginBottom:60}}><p style={{fontFamily:"var(--fm)",fontSize:13,letterSpacing:2,textTransform:"uppercase",color:"var(--acc)",marginBottom:12}}>Tech Stack</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(40px,6vw,64px)",fontWeight:900,letterSpacing:-2.5,lineHeight:1.0}}>Stack & Tools I <span style={{background:"linear-gradient(90deg,#0071e3,#5ac8fa,#30d158,#e056a0,#5856d6,#0071e3)",backgroundSize:"300% 100%",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",animation:"gradientShift 4.5s ease infinite"}}>work with.</span></h2><p style={{fontSize:18,fontWeight:300,color:"var(--ink2)",lineHeight:1.5,marginTop:16,maxWidth:500,margin:"16px auto 0"}}>2+ years across cloud, AI/ML, backend, and DevOps.</p></div></R>
<R d={.1}><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:"20px 32px",marginBottom:64}} className="g3r">{CATS.map((c,i)=>{const barPct=Math.max(0,Math.min(c.pct,(p-i*.06)*c.pct*3));return<div key={c.name} onClick={()=>setActive(i)} style={{cursor:"pointer",padding:"16px 20px",borderRadius:16,background:active===i?"var(--card)":"transparent",border:active===i?"1px solid var(--rule)":"1px solid transparent",transition:"all .3s",boxShadow:active===i?"0 4px 20px rgba(0,0,0,.04)":"none"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",marginBottom:8}}><span style={{fontSize:14,fontWeight:active===i?600:400,color:active===i?c.color:"var(--ink2)",transition:"all .3s"}}>{c.name}</span><span style={{fontFamily:"var(--fm)",fontSize:12,fontWeight:600,color:active===i?c.color:"var(--ink3)"}}>{c.pct}%</span></div><div style={{height:4,background:"var(--bg)",borderRadius:2,overflow:"hidden"}}><div style={{height:"100%",borderRadius:2,background:active===i?c.color:"var(--ink3)",width:`${barPct}%`,transition:"width .3s ease, background .3s",opacity:active===i?1:.4}}/></div></div>})}</div></R>
<R d={.2}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:48,alignItems:"start",minHeight:320}} className="sg"><div style={{display:"flex",flexDirection:"column",gap:4}}>{CATS.map((c,i)=><div key={c.name} onClick={()=>setActive(i)} style={{cursor:"pointer",borderRadius:16,padding:"14px 20px",background:active===i?"var(--card)":"transparent",border:active===i?"1px solid var(--rule)":"1px solid transparent",transition:"all .4s cubic-bezier(.16,1,.3,1)",boxShadow:active===i?"0 4px 16px rgba(0,0,0,.04)":"none"}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:8,height:8,borderRadius:"50%",background:active===i?c.color:"var(--ink3)",transition:"all .3s",transform:active===i?"scale(1.2)":"scale(1)"}}/><span style={{fontSize:16,fontWeight:active===i?600:400,color:active===i?"var(--ink)":"var(--ink3)",transition:"all .3s"}}>{c.name}</span></div><div style={{maxHeight:active===i?200:0,overflow:"hidden",transition:"max-height .5s cubic-bezier(.16,1,.3,1)",marginTop:active===i?12:0}}><p style={{fontSize:14,color:"var(--ink2)",lineHeight:1.6,paddingLeft:20}}>Proficiency: {c.pct}%. Tools and frameworks I use daily to build production-grade systems.</p></div></div>)}</div>
<div style={{display:"flex",alignItems:"center",justifyContent:"center",minHeight:280}}><div style={{background:"var(--card)",border:"1px solid var(--rule)",borderRadius:24,padding:"40px 36px",width:"100%",transition:"all .4s cubic-bezier(.16,1,.3,1)"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:20}}><div style={{width:12,height:12,borderRadius:"50%",background:CATS[active].color}}/><h3 style={{fontFamily:"var(--fd)",fontSize:20,fontWeight:700,color:CATS[active].color,transition:"color .3s"}}>{CATS[active].name}</h3></div><div style={{display:"flex",flexWrap:"wrap",gap:10}}>{CATS[active].techs.map((t,i)=><span key={t} style={{fontFamily:"var(--fm)",fontSize:13,fontWeight:500,padding:"10px 20px",borderRadius:14,background:`${CATS[active].color}10`,border:`1px solid ${CATS[active].color}25`,color:CATS[active].color,animation:`fadeSlideIn .4s cubic-bezier(.16,1,.3,1) ${i*.06}s both`}}>{t}</span>)}</div><div style={{display:"flex",alignItems:"center",gap:16,marginTop:24,paddingTop:20,borderTop:`1px solid ${CATS[active].color}15`}}><div style={{position:"relative",width:48,height:48}}><svg viewBox="0 0 48 48" style={{transform:"rotate(-90deg)"}}><circle cx="24" cy="24" r="20" fill="none" stroke="var(--rule)" strokeWidth="3"/><circle cx="24" cy="24" r="20" fill="none" stroke={CATS[active].color} strokeWidth="3" strokeDasharray={`${CATS[active].pct*1.257} 125.7`} strokeLinecap="round" style={{transition:"all .5s ease"}}/></svg><span style={{position:"absolute",inset:0,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"var(--fm)",fontSize:11,fontWeight:700,color:CATS[active].color}}>{CATS[active].pct}%</span></div><p style={{fontSize:13,color:"var(--ink3)"}}>Proficiency across {CATS[active].techs.length} tools</p></div></div></div></div></R></div>}

function Nav({page,go,theme,toggle}){const[sc,setSc]=useState(false);const[mob,setMob]=useState(false);useEffect(()=>{const h=()=>setSc(scrollY>10);addEventListener("scroll",h);return()=>removeEventListener("scroll",h)},[]);const ng=p=>{go(p);setMob(false);scrollTo({top:0,behavior:"smooth"})};
return<><nav style={{position:"fixed",top:0,left:0,right:0,zIndex:1000,height:48,display:"flex",alignItems:"center",background:"var(--nav)",backdropFilter:"saturate(180%) blur(20px)",WebkitBackdropFilter:"saturate(180%) blur(20px)",borderBottom:sc?"1px solid var(--rule)":"1px solid transparent",transition:"all .3s"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",width:"100%",maxWidth:1200,margin:"0 auto",padding:"0 28px"}}><button onClick={()=>ng("home")} style={{fontFamily:"var(--fd)",fontWeight:700,fontSize:18,color:"var(--ink)",background:"none",border:"none",cursor:"pointer"}}>GMG</button><div className="nd" style={{display:"flex",gap:2}}>{[["home","Home"],["life","Life of GMG"],["thoughts","My Thoughts"]].map(([k,l])=><button key={k} onClick={()=>ng(k)} style={{fontFamily:"var(--fb)",fontSize:12,fontWeight:page===k?500:400,color:page===k?"var(--acc)":"var(--ink2)",background:"none",border:"none",cursor:"pointer",padding:"5px 14px",borderRadius:99,transition:"all .2s"}}>{l}</button>)}</div><div style={{display:"flex",alignItems:"center",gap:6}}>{[{h:D.li,c:"fab fa-linkedin-in"},{h:D.gh,c:"fab fa-github"},{h:D.tw,c:"fab fa-twitter"}].map(s=><a key={s.c} href={s.h} target="_blank" rel="noopener noreferrer" className="nsi" style={{width:28,height:28,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",color:"var(--ink3)",fontSize:12,textDecoration:"none",transition:"all .2s"}}><i className={s.c}/></a>)}<span style={{width:1,height:14,background:"var(--rule)",margin:"0 4px"}}/><button onClick={toggle} style={{width:28,height:28,borderRadius:"50%",border:"none",background:"transparent",cursor:"pointer",fontSize:13,display:"flex",alignItems:"center",justifyContent:"center"}}>{theme==="dark"?"☀️":"🌙"}</button><button className="nb" onClick={()=>setMob(!mob)} style={{display:"none",width:32,height:32,border:"none",background:"none",cursor:"pointer",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:5}}><span style={{display:"block",width:16,height:1.5,background:"var(--ink)",borderRadius:1,transition:"all .3s",transform:mob?"rotate(45deg) translate(3px,3px)":"none"}}/><span style={{display:"block",width:16,height:1.5,background:"var(--ink)",borderRadius:1,transition:"all .3s",opacity:mob?0:1}}/><span style={{display:"block",width:16,height:1.5,background:"var(--ink)",borderRadius:1,transition:"all .3s",transform:mob?"rotate(-45deg) translate(3px,-3px)":"none"}}/></button></div></div></nav>
{mob&&<div style={{position:"fixed",top:48,left:0,right:0,bottom:0,background:"var(--bg)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:16,zIndex:999}}>{[["home","Home"],["life","Life of GMG"],["thoughts","My Thoughts"]].map(([k,l])=><button key={k} onClick={()=>ng(k)} style={{fontFamily:"var(--fb)",fontSize:24,fontWeight:500,color:page===k?"var(--acc)":"var(--ink)",background:"none",border:"none",cursor:"pointer",padding:"12px 24px"}}>{l}</button>)}</div>}</>}

const Footer=()=><footer style={{padding:"48px 24px",textAlign:"center",borderTop:"1px solid var(--rule)",background:"var(--bg2)"}}><div style={{display:"flex",gap:14,justifyContent:"center",marginBottom:14}}>{[{h:D.li,i:"fab fa-linkedin-in"},{h:D.gh,i:"fab fa-github"},{h:D.tw,i:"fab fa-twitter"}].map(s=><a key={s.i} href={s.h} target="_blank" rel="noopener noreferrer" className="nsi" style={{width:40,height:40,borderRadius:"50%",background:"var(--card)",border:"1px solid var(--rule)",display:"flex",alignItems:"center",justifyContent:"center",color:"var(--ink2)",textDecoration:"none",fontSize:16,transition:"all .3s"}}><i className={s.i}/></a>)}</div><p style={{fontSize:13,color:"var(--ink3)"}}>© 2026 Gnana Ganesh M</p></footer>;
const Pill=({children,color})=><span style={{display:"inline-block",fontFamily:"var(--fm)",fontSize:11,fontWeight:600,padding:"5px 14px",borderRadius:99,background:color?`${color}12`:"var(--acctint)",color:color||"var(--acc)",letterSpacing:.3,marginTop:8}}>{children}</span>;
const TiltCard=({children})=>{const ref=useRef(null);const[t,setT]=useState({rx:0,ry:0,sx:50,sy:50});const onM=e=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();const x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;setT({rx:(y-.5)*-14,ry:(x-.5)*14,sx:x*100,sy:y*100})};return<div ref={ref} onMouseMove={onM} onMouseLeave={()=>setT({rx:0,ry:0,sx:50,sy:50})} style={{perspective:800}}><div style={{transform:`rotateX(${t.rx}deg) rotateY(${t.ry}deg)`,transition:"transform .2s ease",background:"var(--card)",border:"1px solid var(--rule)",borderRadius:24,padding:"32px 28px",position:"relative",overflow:"hidden",height:"100%",display:"flex",flexDirection:"column"}}><div style={{position:"absolute",inset:0,background:`radial-gradient(circle at ${t.sx}% ${t.sy}%, rgba(255,255,255,.06), transparent 60%)`,pointerEvents:"none"}}/>{children}</div></div>};
const inp={width:"100%",padding:"14px 18px",fontFamily:"var(--fb)",fontSize:15,border:"1px solid var(--rule)",borderRadius:14,background:"var(--card)",color:"var(--ink)",outline:"none",transition:"all .3s"};

function Home({go}){const[hr,setHr]=useState(false);useEffect(()=>{setTimeout(()=>setHr(true),300)},[]);
const ow=[{text:"Software Engineer",from:"translateX(-40px)",delay:.3},{text:"/",from:"translateY(-20px)",delay:.5},{text:"Cloud Architect",from:"translateY(30px)",delay:.55},{text:"/",from:"translateY(-20px)",delay:.7},{text:"Explorer",from:"translateX(40px)",delay:.75}];
return<>
  <section style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",textAlign:"center",padding:"120px 24px 80px",position:"relative",overflow:"hidden"}}><Particles/><div style={{position:"relative",zIndex:1,display:"flex",flexDirection:"column",alignItems:"center"}}><MagneticPhoto/><div style={{display:"flex",gap:8,alignItems:"center",justifyContent:"center",flexWrap:"wrap",marginBottom:20}}>{ow.map((w,i)=><span key={i} style={{fontFamily:"var(--fm)",fontSize:14,color:w.text==="/"?"var(--ink3)":"var(--acc)",letterSpacing:2,textTransform:"uppercase",display:"inline-block",opacity:hr?1:0,transform:hr?"translate(0)":w.from,transition:`all .6s cubic-bezier(.16,1,.3,1) ${w.delay}s`}}>{w.text}</span>)}</div><NameReveal/><div style={{opacity:hr?1:0,transition:"opacity .8s ease 1.4s",marginTop:20}}><p style={{fontFamily:"var(--fb)",fontSize:"clamp(18px,2.2vw,22px)",fontWeight:300,color:"var(--ink2)"}}>I am a/an <Typer/></p></div><div style={{opacity:hr?1:0,transform:hr?"translateY(0)":"translateY(16px)",transition:"all .6s ease 1.8s",marginTop:36}}><div style={{display:"flex",gap:14,flexWrap:"wrap",justifyContent:"center"}}><a href="#work" style={{display:"inline-flex",padding:"14px 30px",borderRadius:99,background:"var(--acc)",color:"#fff",fontFamily:"var(--fb)",fontSize:16,fontWeight:500,textDecoration:"none"}}>See My Work</a><button onClick={()=>{go("life");scrollTo({top:0,behavior:"smooth"})}} style={{padding:"14px 30px",borderRadius:99,background:"transparent",color:"var(--acc)",border:"1.5px solid var(--acc)",fontFamily:"var(--fb)",fontSize:16,fontWeight:500,cursor:"pointer"}}>Life of GMG</button></div></div></div></section>

  <section id="work" style={{padding:"120px 24px"}}><div style={{maxWidth:1200,margin:"0 auto"}}>
    <R><div style={{textAlign:"center",marginBottom:80}}><p style={{fontFamily:"var(--fm)",fontSize:13,letterSpacing:2,textTransform:"uppercase",color:"var(--acc)",marginBottom:12}}>Experience</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(40px,6vw,64px)",fontWeight:900,letterSpacing:-2.5}}>Where impact<br/><span style={{background:"linear-gradient(90deg,#ff6b6b,#ee5a24,#e056a0,#0071e3,#5ac8fa,#30d158,#ff6b6b)",backgroundSize:"300% 100%",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",animation:"gradientShift 4s ease infinite"}}>was made.</span></h2></div></R>
    <ExpDevice data={D.oracle}/><ExpDevice data={D.accenture}/>
    <R><div style={{padding:"28px 32px",background:"var(--bg2)",borderRadius:20,display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:16}}><div><h3 style={{fontFamily:"var(--fd)",fontSize:18,fontWeight:700}}>SRM Institute of Science & Technology</h3><p style={{fontSize:14,color:"var(--acc)",marginTop:2}}>B.Tech / CSE (Cloud Computing)</p><p style={{fontSize:13,color:"var(--ink3)",marginTop:4}}>First Class with Distinction. 2019 / 2023.</p></div><Pill>Education</Pill></div></R>
  </div></section>

  <section style={{padding:"120px 24px",background:"var(--bg2)"}}><div style={{maxWidth:1300,margin:"0 auto",paddingLeft:48}}>
    <R><div style={{textAlign:"center",marginBottom:48}}><p style={{fontFamily:"var(--fm)",fontSize:13,letterSpacing:2,textTransform:"uppercase",color:"var(--acc)",marginBottom:12}}>Projects</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(36px,5.5vw,60px)",fontWeight:900,letterSpacing:-2.5}}><span style={{background:"linear-gradient(90deg,#667eea,#e056a0,#ff6b6b,#ee5a24,#30d158,#0071e3,#667eea)",backgroundSize:"300% 100%",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",animation:"gradientShift 5s ease infinite"}}>Built from scratch.</span></h2></div></R>
    <R d={.1}><ProjectGrid/></R>
  </div></section>

  <section style={{padding:"120px 24px",background:"var(--bg2)"}}><div style={{maxWidth:1200,margin:"0 auto"}}><ScrollSkills/></div></section>
  <ProvenImpact/>

  <section style={{padding:"120px 24px"}}><div style={{maxWidth:1300,margin:"0 auto",paddingLeft:48}}>
    <R><div style={{textAlign:"center",marginBottom:48}}><p style={{fontFamily:"var(--fm)",fontSize:13,letterSpacing:2,textTransform:"uppercase",color:"var(--acc)",marginBottom:12}}>Certifications</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(32px,4.5vw,52px)",fontWeight:800,letterSpacing:-2}}><span style={{background:"linear-gradient(90deg,#FF9900,#e056a0,#7B42BC,#326ce5,#A51C30,#FF9900)",backgroundSize:"300% 100%",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent",animation:"gradientShift 6s ease infinite"}}>Credentials that back it up.</span></h2></div></R>
    <R d={.1}><CertShowcase/></R>
  </div></section>

  <section id="contact" style={{padding:"120px 24px",position:"relative",overflow:"hidden"}}>
    <div style={{position:"absolute",inset:0,background:"var(--bg)"}}/>
    <div style={{position:"absolute",top:"-20%",right:"-10%",width:600,height:600,borderRadius:"50%",background:"radial-gradient(circle,rgba(0,113,227,.07),transparent 70%)",filter:"blur(60px)",animation:"floatBlob 8s ease infinite"}}/>
    <div style={{position:"absolute",bottom:"-15%",left:"-5%",width:500,height:500,borderRadius:"50%",background:"radial-gradient(circle,rgba(90,200,250,.07),transparent 70%)",filter:"blur(60px)",animation:"floatBlob 10s ease infinite reverse"}}/>
    <div style={{maxWidth:1100,margin:"0 auto",position:"relative",zIndex:1}}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:60,alignItems:"start"}} className="sg">
      <R dir="left"><div><p style={{fontFamily:"var(--fm)",fontSize:13,letterSpacing:2,textTransform:"uppercase",color:"var(--acc)",marginBottom:12}}>Get in Touch</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(40px,6vw,64px)",fontWeight:900,letterSpacing:-2.5,lineHeight:1.0}}><span style={{color:"var(--acc)"}}>Say hello.</span><br/>Let's connect.</h2><p style={{fontSize:18,fontWeight:300,color:"var(--ink2)",lineHeight:1.6,marginTop:20,maxWidth:400}}>Open to collaborations and good conversations.</p>
        <div style={{display:"flex",flexDirection:"column",gap:18,marginTop:36}}>{[{i:"fas fa-envelope",l:D.email,h:`mailto:${D.email}`},{i:"fas fa-phone",l:D.phone,h:`tel:${D.phone}`},{i:"fas fa-map-marker-alt",l:D.location,h:D.map}].map(c=><a key={c.l} href={c.h} target="_blank" rel="noopener noreferrer" style={{display:"flex",alignItems:"center",gap:14,textDecoration:"none",color:"var(--ink2)",fontSize:16}}><i className={c.i} style={{width:20,textAlign:"center",color:"var(--acc)",fontSize:17}}/>{c.l}</a>)}</div>
        <div style={{marginTop:36,padding:"28px 32px",borderRadius:24,background:"var(--acctint)"}}><p style={{fontFamily:"var(--fd)",fontWeight:700,fontSize:16,color:"var(--acc)",marginBottom:12}}>Currently open to</p>{["Open source collaborations","Speaking & mentoring"].map(x=><p key={x} style={{fontSize:15,color:"var(--ink2)",display:"flex",alignItems:"center",gap:10,marginTop:8}}><span style={{color:"var(--acc)",fontWeight:700,fontSize:16}}>✓</span>{x}</p>)}</div>
      </div></R>
      <R dir="right" d={.1}><form action={D.form} method="post" style={{display:"flex",flexDirection:"column",gap:18,background:"var(--card)",border:"1px solid var(--rule)",borderRadius:28,padding:40,boxShadow:"0 24px 80px rgba(0,0,0,.07)"}}><h3 style={{fontFamily:"var(--fd)",fontSize:22,fontWeight:700,marginBottom:4}}>Drop a message</h3><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><input name="name" placeholder="Your name" required style={inp}/><input name="email" type="email" placeholder="Email" required style={inp}/></div><input name="subject" placeholder="Subject" style={inp}/><textarea name="message" placeholder="Your message..." required rows={5} style={{...inp,resize:"vertical",minHeight:130}}/><button type="submit" style={{padding:"16px 30px",borderRadius:99,background:"var(--acc)",color:"#fff",fontFamily:"var(--fb)",fontSize:17,fontWeight:600,border:"none",cursor:"pointer",width:"100%",boxShadow:"0 6px 24px rgba(0,113,227,.3)"}}>Send Message</button></form></R>
    </div></div>
  </section>
  <Footer/>
</>}

function Life(){return<><section style={{minHeight:"85vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",textAlign:"center",padding:"120px 24px 80px"}}><R><p style={{fontFamily:"var(--fm)",fontSize:14,color:"var(--acc)",letterSpacing:2,textTransform:"uppercase",marginBottom:20}}>Beyond the Code</p></R><R d={.1}><h1 style={{fontFamily:"var(--fd)",fontSize:"clamp(56px,11vw,100px)",fontWeight:900,lineHeight:.95,letterSpacing:-4}}>Life of<br/><span style={{background:"linear-gradient(135deg,var(--acc),#34aadc,#5ac8fa)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>GMG.</span></h1></R><R d={.2}><p style={{fontSize:"clamp(18px,2.2vw,22px)",fontWeight:300,color:"var(--ink2)",maxWidth:500,lineHeight:1.5,marginTop:24}}>A rider, a photographer, a thinker, and an explorer.</p></R></section>
<section style={{padding:"100px 24px",background:"linear-gradient(180deg,var(--bg2),var(--bg))"}}><div style={{maxWidth:800,margin:"0 auto",textAlign:"center"}}><R><p style={{fontFamily:"var(--fd)",fontSize:"clamp(24px,4vw,40px)",fontWeight:300,lineHeight:1.35,letterSpacing:-.5,position:"relative"}}><span style={{fontSize:80,fontWeight:900,color:"var(--acc)",opacity:.08,position:"absolute",top:-24,left:"50%",transform:"translateX(-50%)",fontFamily:"var(--fd)"}}>"</span>The best code I have ever written runs on two wheels, and the best architecture I have designed was the route to the next sunrise.</p><p style={{fontSize:15,color:"var(--ink3)",marginTop:24}}>/ Gnana Ganesh</p></R></div></section>
<section style={{padding:"120px 24px"}}><div style={{maxWidth:1100,margin:"0 auto"}}><R><div style={{textAlign:"center",marginBottom:60}}><p style={{fontFamily:"var(--fm)",fontSize:13,letterSpacing:2,textTransform:"uppercase",color:"var(--acc)",marginBottom:12}}>My Passions</p><h2 style={{fontFamily:"var(--fd)",fontSize:"clamp(36px,5vw,56px)",fontWeight:800,letterSpacing:-2}}>What fuels me.</h2></div></R>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:24}} className="g2r">{D.passions.map((p,i)=><R key={p.title} d={i*.07}><TiltCard><div style={{fontSize:48,marginBottom:12}}>{p.emoji}</div><h3 style={{fontFamily:"var(--fd)",fontSize:22,fontWeight:700,letterSpacing:-.3,marginBottom:8}}>{p.title}</h3><p style={{fontSize:15,color:"var(--ink2)",lineHeight:1.6}}>{p.desc}</p><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:16}}>{p.tags.map(t=><Pill key={t} color={p.color}>{t}</Pill>)}</div></TiltCard></R>)}</div></div></section><Footer/></>}

function Thoughts(){return<><section style={{minHeight:"85vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",textAlign:"center",padding:"120px 24px 80px"}}><R><p style={{fontFamily:"var(--fm)",fontSize:14,color:"var(--acc)",letterSpacing:2,textTransform:"uppercase",marginBottom:20}}>Open Thinking</p></R><R d={.1}><h1 style={{fontFamily:"var(--fd)",fontSize:"clamp(56px,11vw,100px)",fontWeight:900,lineHeight:.95,letterSpacing:-4}}>My<br/><span style={{background:"linear-gradient(135deg,#5856d6,var(--acc),#5ac8fa)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>Thoughts.</span></h1></R></section>
<section style={{padding:"60px 24px 120px"}}><div style={{maxWidth:1100,margin:"0 auto"}}><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:24}} className="g3r">{D.blogs.map((b,i)=><R key={b.title} d={i*.08}><TiltCard><Pill color={b.color}>{b.tag}</Pill><h3 style={{fontFamily:"var(--fd)",fontSize:22,fontWeight:700,letterSpacing:-.3,marginTop:16,marginBottom:10,lineHeight:1.25}}>{b.title}</h3><p style={{fontSize:15,color:"var(--ink2)",lineHeight:1.6,flex:1}}>{b.excerpt}</p><p style={{fontSize:12,color:"var(--ink3)",marginTop:20}}>Coming Soon</p></TiltCard></R>)}</div></div></section><Footer/></>}

export default function App(){const[page,setPage]=useState("home");const[theme,toggle]=useTheme();const[loaded,setLoaded]=useState(false);useEffect(()=>{setTimeout(()=>setLoaded(true),2200)},[]);
return<div style={{background:"var(--bg)",color:"var(--ink)",minHeight:"100vh",transition:"background .4s,color .4s"}}><style>{`
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@200;300;400;500;600;700;800;900&family=DM+Sans:ital,opsz,wght@0,9..40,200;0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400&family=JetBrains+Mono:wght@400;500;600&display=swap');
:root{--bg:#fbfbfd;--bg2:#f5f5f7;--card:#fff;--nav:rgba(251,251,253,.72);--ink:#1d1d1f;--ink2:#6e6e73;--ink3:#86868b;--acc:#0071e3;--acctint:rgba(0,113,227,.07);--rule:rgba(0,0,0,.09);--fd:'Outfit',-apple-system,sans-serif;--fb:'DM Sans',-apple-system,sans-serif;--fm:'JetBrains Mono',monospace}
[data-theme="dark"]{--bg:#000;--bg2:#111;--card:#1c1c1e;--nav:rgba(0,0,0,.72);--ink:#f5f5f7;--ink2:#a1a1a6;--ink3:#6e6e73;--acc:#2997ff;--acctint:rgba(41,151,255,.1);--rule:rgba(255,255,255,.08)}
*{margin:0;padding:0;box-sizing:border-box}html{scroll-behavior:smooth;-webkit-font-smoothing:antialiased}body{font-family:var(--fb);overflow-x:hidden}
::selection{background:var(--acc);color:#fff}::-webkit-scrollbar{width:6px}::-webkit-scrollbar-thumb{background:var(--rule);border-radius:3px}
.hideScroll::-webkit-scrollbar{display:none}.hideScroll{scrollbar-width:none}
input:focus,textarea:focus{border-color:var(--acc)!important;box-shadow:0 0 0 3px var(--acctint)!important;transform:translateY(-1px)}
.nsi:hover{color:var(--acc)!important;background:var(--acctint)}
@keyframes blink{0%,100%{opacity:1}50%{opacity:0}}
@keyframes spinSlow{to{transform:rotate(360deg)}}
@keyframes floatBlob{0%,100%{transform:translate(0,0)}50%{transform:translate(20px,-20px)}}
@keyframes gradientShift{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}
@keyframes fadeSlideIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
@keyframes loaderRing{0%{transform:rotate(0);opacity:.3}50%{opacity:1}100%{transform:rotate(360deg);opacity:.3}}
@keyframes loaderScale{0%,100%{transform:scale(1);opacity:.6}50%{transform:scale(1.15);opacity:1}}
@media(max-width:868px){.nd{display:none!important}.nb{display:flex!important}.sg{grid-template-columns:1fr!important}.g3r{grid-template-columns:1fr!important}.g2r{grid-template-columns:1fr!important}.skg{grid-template-columns:1fr!important}}
`}</style>
{!loaded&&<div style={{position:"fixed",inset:0,zIndex:9999,background:"var(--bg)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}>
  <div style={{position:"relative",width:60,height:60,marginBottom:28}}><div style={{position:"absolute",inset:0,borderRadius:"50%",border:"3px solid var(--acc)",borderTopColor:"transparent",animation:"loaderRing 1.2s linear infinite"}}/><div style={{position:"absolute",inset:8,borderRadius:"50%",border:"3px solid #5ac8fa",borderBottomColor:"transparent",animation:"loaderRing 1.8s linear infinite reverse"}}/><div style={{position:"absolute",inset:16,borderRadius:"50%",background:"var(--acc)",opacity:.15,animation:"loaderScale 1.5s ease infinite"}}/></div>
  <p style={{fontFamily:"var(--fd)",fontSize:18,fontWeight:400,color:"var(--ink3)"}}>just a sec!</p>
  <p style={{fontFamily:"var(--fd)",fontSize:32,fontWeight:800,letterSpacing:-1.5,marginTop:6}}><span style={{color:"var(--ink)"}}>GMG</span> <span style={{background:"linear-gradient(135deg,var(--acc),#34aadc,#5ac8fa)",WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>Cooking 4 you...</span></p>
</div>}
<Nav page={page} go={setPage} theme={theme} toggle={toggle}/>
{page==="home"&&<Home go={setPage}/>}{page==="life"&&<Life/>}{page==="thoughts"&&<Thoughts/>}
</div>}
